---
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: gobottle
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X github.com/isometry/gobottle/cmd.Version={{ .Version }}
        -X github.com/isometry/gobottle/cmd.Commit={{ .ShortCommit }}
        -X github.com/isometry/gobottle/cmd.Date={{ .CommitDate }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  version_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  draft: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
